volumes:
  psql:
  go:
services:
  db:
    container_name: rest-go-db
    image: postgres:15.8-alpine3.20
    volumes:
      - psql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
  api:
    container_name: rest-go-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: air -c .air.toml
    volumes:
      - .:/app
      - go:/go
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 1323:1323
